DisablePathCorrection: false
EnablePathEscape: false
FireMethodNotAllowed: true
DisableBodyConsumptionOnUnmarshal: true
TimeFormat: Mon, 01 Jan 2006 15:04:05 GMT
Charset: UTF-8

Mysql:
  Port: 3306
  Name: root
  Pwd: root
  Ip: 127.0.0.1
  DBName: go